require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Include:
    - "spec/**/*"
  Exclude:
    - "lib/**/*"
    - "bin/**/*"
    - "db/schema.rb"

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
